name: Run PHPUnit tests

on:
  workflow_call:
    inputs:
      OS:
        description: 'Operating system to run tests on'
        required: false
        type: 'string'
        default: 'ubuntu-latest'
      PHP:
        description: 'The version of PHP to use, in the format of X.Y'
        required: false
        type: 'string'
        default: '7.2'
      TEST_SUITE:
        description: 'The PHPUnit test suite to use'
        required: false
        type: 'string'
        default: 'all'

env:
  LOCAL_PHP: ${{ inputs.PHP }}-fpm
  PHPUNIT_CONFIG: phpunit.xml.dist

jobs:
  prepare:
    name: ${{ inputs.OS }}
    runs-on: ${{ inputs.OS }}
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ inputs.PHP }}'
          tools: phpunit-polyfills
          extensions: zip, pdo_sqlite, sqlite3

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          ignore-cache: "yes"
          composer-options: "--optimize-autoloader"

  unit:
    name: Run PHPUnit unit tests
    runs-on: ${{ inputs.OS }}

    steps:
      - name: Run PHPUnit unit tests
        if: ${{ contains( fromJSON( '["unit", "all"]' ), inputs.TEST_SUITE ) }}
        run: phpunit --testsuite unit --testdox

  e2e:
    name: Run PHPUnit e2e tests
    runs-on: ${{ inputs.OS }}
    timeout-minutes: 5

    steps:
      - name: Run PHPUnit e2e tests
        if: ${{ contains( fromJSON( '["e2e", "all"]' ), inputs.TEST_SUITE ) }}
        run: phpunit --testsuite e2e --testdox
