name: PHPUnit Tests Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      PHP:
        description: 'pick which PHP version to run with'
        type: choice
        options:
          - all
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
        required: false
        default: all
      OS:
        description: 'pick which OS version to run on'
        type: choice
        options:
          - all
          - ubuntu-latest
          - macos-latest
          - windows-latest
        required: false
        default: all
      TEST_SUITE:
        description: 'pick which PHPUnit test suite to run'
        type: choice
        options:
          - all
          - unit
          - e2e
        required: false
        default: all

jobs:
  test:
    name: PHP ${{ matrix.php }}
    uses: ./.github/workflows/phpunit-tests-run.yml
    permissions:
      contents: read
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        os: ${{ ( github.event.inputs.OS == 'all' && fromJSON('["ubuntu-latest", "macos-latest", "windows-latest"]') ) || github.event.inputs.OS }}
        php: ${{ ( github.event.inputs.PHP == 'all' && fromJSON('["7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]') ) || github.event.inputs.OS }}